#index:
#    path: /
#    controller: App\Controller\DefaultController::index

pizza_index:
  path: /pizza
  controller: App\Controller\PizzaController::index
  methods: GET

pizza_add:
  path: /pizza
  controller: App\Controller\PizzaController::add
  methods: POST

ingridient_index:
  path: /ingridient/{?id}
  controller: App\Controller\IngridientController::index
  methods: GET

ingridient_add:
  path: /ingridient/add
  controller: App\Controller\IngridientController::add
  methods: POST

ingridient_update:
  path: /ingridient/{id}/update
  controller: App\Controller\IngridientController::update
  methods: POST

pizza_addIngridient:
  path: /pizza/{id}/ingridient/add
  controller: App\Controller\PizzaController::addIngridient
  methods: POST

pizza_appendIngridient:
  path: /pizza/{id}/ingridient/append
  controller: App\Controller\PizzaController::apendIngridient
  methods: POST

pizza_info:
  path: /pizza/{id}/info
  controller: App\Controller\PizzaController::info
  methods: GET
