#index:
#    path: /
#    controller: App\Controller\DefaultController::index

pizza_index:
  path: /pizza
  controller: App\Controller\PizzaController::index
  methods: GET

pizza_add:
  path: /pizza
  controller: App\Controller\PizzaController::add
  methods: POST

ingridient_index:
  path: /ingridient/{?id}
  controller: App\Controller\IngridientController::index
  methods: GET

pizza_appendIngridient:
  path: /pizza/{id}
  controller: App\Controller\PizzaController::appendIngridient
  methods: POST

pizza_info:
  path: /pizza/{id}/info
  controller: App\Controller\PizzaController::info
  methods: GET
