#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\PizzaController::index
  methods: GET

details:
  path: /{id}/details
  controller: App\Controller\PizzaController::pizzaDetails
  methods: GET

pizza_new:
  path: /pizza/new
  controller: App\Controller\PizzaController::new
  methods: GET|POST

pizza_update:
  path: /pizza/{id}/update
  controller: App\Controller\PizzaController::update
  methods: GET|POST

pizza_remove:
  path: /pizza/{id}/remove
  controller: App\Controller\PizzaController::remove
  methods: GET

ingridient_list:
  path: /ingridient/list
  controller: App\Controller\IngridientController::index
  methods: GET

ingridient_new:
  path: /ingridient/new
  controller: App\Controller\IngridientController::new
  methods: GET|POST

ingridient_update:
  path: /ingridient/{id}/update
  controller: App\Controller\IngridientController::update
  methods: GET|POST

ingridient_remove:
  path: /ingridient/{id}/remove
  controller: App\Controller\IngridientController::remove
  methods: GET

pizza_ingridient_append:
  path: /pizza/{pizza_id}/ingridient/{ingridient_id}/append
  controller: App\Controller\PizzaController::apendIngridient
  methods: GET

pizza_ingridient_remove:
  path: /pizza/{pizza_id}/ingridient/{ingridient_id}/remove
  controller: App\Controller\PizzaController::removeIngridient
  methods: GET

ingridient_pizza_append_ingridient_list:
  path: /pizza/{id}/ingridient/append
  controller: App\Controller\PizzaController::pizzaAppendIngridientList
  methods: GET
